# An example Trunk.toml with all possible fields along with their defaults.

[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/"

[watch]
# Additional paths to ignore.
ignore = []

[serve]
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = false

[clean]
# The output dir for all final assets.
dist = "dist"
# Optionally perform a cargo clean.
cargo = false

## proxy
# Proxies are optional, and default to `None`.
# Proxies are only run as part of the `trunk serve` command.

[[proxy]]
# This proxy example has a backend and a rewrite field. Requests received on `rewrite` will be
# proxied to the backend after rewriting the `rewrite` prefix to the `backend`'s URI prefix.
# E.G., `/api/v1/resource/x/y/z` -> `/resource/x/y/z`
rewrite = "/api/v1/"
backend = "http://localhost:9000/"

[[proxy]]
# This proxy specifies only the backend, which is the only required field. In this example,
# request URIs are not modified when proxied.
backend = "http://localhost:9000/api/v2/"

# Compression of assets is optional and requires `trunk`
# to be built with a compression feature enabled.
#
# Mutliple compressors may be specified.
[[compression]]
# Specifies the compression algorithm to be used. You must
# specify the algorithm for each compression array.
algorithm = "gzip"
# Options to pass to the compression algorithm.
options = { level = 9 }
# A RegExp test to pass to include assets that pass the RegExp test. Optional.
test = "/\.(js|css|png|jp(e)?g|wasm)(\?.*)?$/i"
# Allow for exclusion of certain assets via glob. Optional.
exclude = ["favicon.ico", "*.gz"] 
# Size of asset (in bytes) that should be compressed. Optional.
threshold = 8192
# Minimum compressed asset size ratio for output. Optional.
ratio = 0.8
